name: zebra_print_plugin
description: A new Flutter project.
version: 0.0.1
homepage: https://github.com/subhashPetro/zebra_print_plugin.git
authors:
  - Subhash Chandra Shukla
  - Ayushi Gupta

environment:
  sdk: '>=2.19.4 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.zebra_print_plugin
        pluginClass: ZebraPrintPlugin
      ios:
        pluginClass: ZebraPrintPlugin

